#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine to
# respect the requirements:
#+ Install nginx
#+ Nginx should be listening on port 80
#+ When querying Nginx at its root / with a GET request
# (requesting a page) using curl, it must return a page
# that contains the string Hello world!

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
