#!/usr/bin/env bash
# install nginx server and configure it to port 80, set the redirect_me page, 404 not found page and the X-served-By header
apt-get -y update
apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
        listen 80;
        listen [::]:80 default_server;
        
        add_header X-Served-By $HOSTNAME;
                
        root /var/www/html/;
        index index.html index.htm index.html-debian.html;
                
        location /redirect_me{
            return 301 https://www.github.com/Dikachis;
        }
        
        error_page 404 /404.html;
        location /404{
            root /var/www/html/;
            internal;
        }    
    
}" > /etc/nginx/sites-available/default

service nginx restart
