#!/usr/bin/env bash
# Install and configure HAproxy on your load balancer server

ufw allow 1344
sudo apt-get update
sudo apt-get install -y haproxy=2.0.\*

printf %s "
backend web-backend
        balance roundrobin
        option forwardfor
        server 9318-web-01 3.236.115.124:80 check
        server 9318-web-02 3.227.233.5:80 check
frontend proxynode
        bind *:80
        mode http
        default_backend web-backend
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
