#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.
# Export all databases to backup.sql //mysqldump -u [username] -p [database name] > [database name].sql
sudo mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czvf "$(date +%d-%m-%Y).tar.gz" backup.sql
