#!/usr/bin/env bash
# This script display listening ports
# That only shows listening sockets
# That shows the PID and name of the program to which each socket belongs

# netstat --listening --program
# OR
# netstat -lp
# OR
netstat -ltup
