#!/usr/bin/env bash
# Debbugging webserver
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default ; sed -i 's/ ipv6only=on//g' /etc/nginx/sites-enabled/default 
sed -i 's/ ipv6only=on//g' /etc/nginx/sites-available/default 
service nginx restart
