#!/usr/bin/env bash
# This script create the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal


# ps | pgrep bash | head -n 1 | awk '{print $1}' > /var/run/myscript.pid    # redirect pid

# OR

echo "$$" > /var/run/myscript.pid

delete_func()
{
	rm /var/run/myscript.pid
	exit
}

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && delete_func' SIGTERM
  trap 'delete_func' SIGQUIT
done
