#!/usr/bin/env bash
# This script displays number from 1-20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

number=1

while [ "$number" -le "20" ]
do
    echo "$number"
    case $number in
        "4" )
            echo "bad luck from China" ;;
        "9" )
            echo "bad luck from Japan" ;;
        "17" )
            echo "bad luck from Italy" ;;
        * )
            ;;
    esac

    number=$(( number + 1 ))
done
