#!/usr/bin/env bash
# configure the container to run nginx under nginx user on port 8080
chown nginx:nginx /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/sites-available/default
chmod u+rwx /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill apache2
su nginx service nginx restart

# OR
#!/usr/bin/env bash
# configure the container to run nginx under nginx user on port 8080
# sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
# sed -i "s/80 /8080 /g" /etc/nginx/sites-available/default
# chown -R nginx:nginx /etc/nginx
# chmod 755 /etc/nginx/nginx.conf
# pkill -9 apache
# su nginx -c "service nginx restart"
